spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/aiflowy?useInformationSchema=true&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: aiflowy
    password: 123456
springdoc:
  api-docs:
    enabled: false